name: PR

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      # Documentation
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE'
      # GitHub repository configuration
      - '.github/dependabot.yaml'
      - '.github/settings.yml'
      - '.github/SECURITY.md'
      - '.github/release-header.md'
      # Editor and formatting configuration
      - '.editorconfig'
      - '.prettierrc'
      - '.prettierignore'
      # Playground (has its own workflows)
      - 'internal/playground/**'
      # Ansible infrastructure
      - 'platform/ansible/**'

# Only allow one of these to run per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write # Dependabot

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup CI environment
        uses: ./.github/actions/setup

      - name: Lint Go
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          skip-cache: true
          args: --verbose
          working-directory: ./

      - name: Biome
        run: biome ci .

      - name: Lint Terraform
        run: |
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          brew install tflint
          make lint
        working-directory: ./platform/terraform

      - name: Diff
        run: git diff

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup CI environment
        uses: ./.github/actions/setup

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Test Go
        # TODO, add race.
        run: |
          export SOPS_AGE_KEY="${{ secrets.ORG_AGE_SECRET }}"
          go test $(go list ./... | grep -v '/internal/mocks') -coverprofile=./coverage.out -covermode=atomic

      - name: Test JS
        run: pnpm test:js

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          verbose: true

      - name: Diff
        run: git diff

  secret-scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.ORG_GITLEAKS_LICENSE }}
